version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          DB_NAME: rolorex_test
          DB_USER: rolorex
          DB_PASSWORD: rolorex
          DB_HOST: localhost
      - image: circleci/postgres
        environment:
          POSTGRES_USER: rolorex
          POSTGRES_PASSWORD: rolorex
          POSTGRES_DB: rolorex_test
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install Dependencies
          command: pip install --user -r dev-requirements.txt
      - python/save-cache
      - run:
          name: Run Tests
          command: python -m coverage run manage.py test
      - run:
          name: Generate Coverage Reports
          command: python -m coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: htmlcov
workflows:
  main:
    jobs:
      - build
