# Generated by Django 3.0.5 on 2020-04-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyaccess',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
